# Generated by Django 5.0.1 on 2024-02-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="stripe_session_id",
            field=models.TextField(blank=True),
        ),
    ]
